services:
  - type: web
    name: home-price-estimator
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1